name: "Deploy Pokedex"

on:
  push:
    tags:
      - "Pokedex/v*"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - run: dotnet restore
      - run: dotnet build  --no-restore
      - run: dotnet publish SalihEkici_Pokedex/SalihEkici_Pokedex.csproj -c Release --self-contained -r win-x64 --no-build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact_Pokedex
          path: Release
